package com.papa.baguwen1.baguwen1.dao.pojo;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_file
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TFile implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.backedUp
     *
     * @mbg.generated
     */
    private Boolean backedup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_file
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.id
     *
     * @return the value of t_file.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.id
     *
     * @param id the value for t_file.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.name
     *
     * @return the value of t_file.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.name
     *
     * @param name the value for t_file.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.type
     *
     * @return the value of t_file.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.type
     *
     * @param type the value for t_file.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.content
     *
     * @return the value of t_file.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.content
     *
     * @param content the value for t_file.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.backedUp
     *
     * @return the value of t_file.backedUp
     *
     * @mbg.generated
     */
    public Boolean getBackedup() {
        return backedup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.backedUp
     *
     * @param backedup the value for t_file.backedUp
     *
     * @mbg.generated
     */
    public void setBackedup(Boolean backedup) {
        this.backedup = backedup;
    }
}