package com.papa.baguwen1.baguwen1.dao.mapper;

import com.papa.baguwen1.baguwen1.dao.pojo.TFile;
import com.papa.baguwen1.baguwen1.dao.pojo.TFileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbg.generated
     */
    long countByExample(TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbg.generated
     */
    int deleteByExample(TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbg.generated
     */
    int insert(TFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbg.generated
     */
    int insertSelective(TFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbg.generated
     */
    List<TFile> selectByExample(TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbg.generated
     */
    TFile selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TFile record, @Param("example") TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TFile record, @Param("example") TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TFile record);
}